import os

lines = []
lines.append('#include "QueryEngine.h"')
lines.append('#include "Lexer.h"')
lines.append('#include "Parser.h"')
lines.append('#include "AST.h"')
lines.append('#include <sstream>')
lines.append('#include <stdexcept>')
lines.append('#include <algorithm>')
lines.append('')
lines.append('std::string QueryResult::to_string() const {')
lines.append('    if (!ok) return "ERROR: " + message;')
lines.append('    if (!message.empty()) return message;')
lines.append('    if (rows.empty()) return "(0 rows)";')
lines.append('    std::ostringstream ss;')
lines.append('    for (size_t i = 0; i < columns.size(); i++) {')
lines.append('        ss << columns[i];')
lines.append('        if (i + 1 < columns.size()) ss << " | ";')
lines.append('    }')
lines.append('    ss << "\\n";')
lines.append('    for (auto &row : rows) {')
lines.append('        for (size_t i = 0; i < row.size(); i++) {')
lines.append('            ss << value_to_str(row[i]);')
lines.append('            if (i + 1 < row.size()) ss << " | ";')
lines.append('        }')
lines.append('        ss << "\\n";')
lines.append('    }')
lines.append('    return ss.str();')
lines.append('}')
lines.append('')
lines.append('QueryEngine::QueryEngine(std::shared_ptr<Catalog> catalog,')
lines.append('                         std::shared_ptr<BufferPool> pool,')
lines.append('                         std::shared_ptr<DiskManager> disk,')
lines.append('                         std::shared_ptr<BufferPool> idx_pool,')
lines.append('                         std::shared_ptr<DiskManager> idx_disk)')
lines.append('    : catalog_(std::move(catalog))')
lines.append('    , pool_(std::move(pool))')
lines.append('    , disk_(std::move(disk))')
lines.append('    , idx_mgr_(std::make_shared<IndexManager>(idx_pool, idx_disk)) {}')
lines.append('')
lines.append('HeapFile& QueryEngine::get_heap(const std::string &name) {')
lines.append('    auto it = heaps_.find(name);')
lines.append('    if (it != heaps_.end()) return *it->second;')
lines.append('    heaps_[name] = std::make_shared<HeapFile>(name, pool_, disk_);')
lines.append('    return *heaps_[name];')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::execute(const std::string &sql) {')
lines.append('    try {')
lines.append('        std::string up = sql;')
lines.append('        std::transform(up.begin(), up.end(), up.begin(), ::toupper);')
lines.append('        if (up.rfind("CREATE INDEX", 0) == 0) {')
lines.append('            size_t on_pos = up.find(" ON ");')
lines.append('            size_t lp_pos = sql.find(40);')
lines.append('            size_t rp_pos = sql.find(41);')
lines.append('            if (on_pos == std::string::npos || lp_pos == std::string::npos)')
lines.append('                return {false, "syntax: CREATE INDEX ON table (column)"};')
lines.append('            std::string table  = sql.substr(on_pos + 4, lp_pos - on_pos - 4);')
lines.append('            std::string column = sql.substr(lp_pos + 1, rp_pos - lp_pos - 1);')
lines.append('            auto trim = [](std::string s) {')
lines.append('                size_t a = s.find_first_not_of(" \\t");')
lines.append('                size_t b = s.find_last_not_of(" \\t");')
lines.append('                return (a == std::string::npos) ? "" : s.substr(a, b-a+1);')
lines.append('            };')
lines.append('            return exec_create_index(trim(table), trim(column));')
lines.append('        }')
lines.append('        Lexer lexer(sql);')
lines.append('        auto tokens = lexer.tokenize();')
lines.append('        Parser parser(std::move(tokens));')
lines.append('        Statement stmt = parser.parse();')
lines.append('        switch (stmt.type) {')
lines.append('            case StmtType::CREATE_TABLE: return exec_create_table(stmt.create_table);')
lines.append('            case StmtType::DROP_TABLE:   return exec_drop_table(stmt.drop_table);')
lines.append('            case StmtType::SHOW_TABLES:  return exec_show_tables();')
lines.append('            case StmtType::DESCRIBE:     return exec_describe(stmt.describe);')
lines.append('            case StmtType::INSERT:       return exec_insert(stmt.insert);')
lines.append('            case StmtType::SELECT:       return exec_select(stmt.select);')
lines.append('            case StmtType::DELETE:       return exec_delete(stmt.del);')
lines.append('            case StmtType::UPDATE:       return exec_update(stmt.update);')
lines.append('            default: return {false, "unsupported statement"};')
lines.append('        }')
lines.append('    } catch (std::exception &e) {')
lines.append('        return {false, e.what()};')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_create_table(const CreateTableStmt &s) {')
lines.append('    TableDef def(s.table);')
lines.append('    for (auto &c : s.columns) def.add_column(c);')
lines.append('    if (!catalog_->create_table(std::move(def)))')
lines.append('        return {false, "table \'" + s.table + "\' already exists"};')
lines.append('    return {true, "OK: table \'" + s.table + "\' created"};')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_drop_table(const DropTableStmt &s) {')
lines.append('    if (!catalog_->drop_table(s.table))')
lines.append('        return {false, "table \'" + s.table + "\' not found"};')
lines.append('    heaps_.erase(s.table);')
lines.append('    return {true, "OK: table \'" + s.table + "\' dropped"};')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_show_tables() {')
lines.append('    auto tables = catalog_->list_tables();')
lines.append('    QueryResult r;')
lines.append('    r.columns = {"table_name"};')
lines.append('    for (auto &t : tables) r.rows.push_back({t});')
lines.append('    return r;')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_describe(const DescribeStmt &s) {')
lines.append('    const TableDef *def = catalog_->get_table(s.table);')
lines.append('    if (!def) return {false, "table \'" + s.table + "\' not found"};')
lines.append('    QueryResult r;')
lines.append('    r.columns = {"column", "type", "nullable", "primary_key"};')
lines.append('    for (auto &c : def->columns)')
lines.append('        r.rows.push_back({c.name, std::string(dtype_str(c.type)),')
lines.append('                          std::string(c.nullable ? "YES" : "NO"),')
lines.append('                          std::string(c.is_primary_key ? "YES" : "NO")});')
lines.append('    return r;')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_create_index(const std::string &table, const std::string &column) {')
lines.append('    if (!catalog_->table_exists(table))')
lines.append('        return {false, "table \'" + table + "\' not found"};')
lines.append('    const TableDef *def = catalog_->get_table(table);')
lines.append('    int col_idx = def->column_index(column);')
lines.append('    if (col_idx < 0) return {false, "column \'" + column + "\' not found"};')
lines.append('    if (def->columns[col_idx].type != DataType::INT)')
lines.append('        return {false, "indexes only supported on INT columns for now"};')
lines.append('    idx_mgr_->create_index(table, column);')
lines.append('    std::vector<DataType> types;')
lines.append('    for (auto &c : def->columns) types.push_back(c.type);')
lines.append('    HeapFile &heap = get_heap(table);')
lines.append('    BTree *idx = idx_mgr_->get_index(table, column);')
lines.append('    heap.scan([&](RID rid, const char *data, uint16_t len) {')
lines.append('        auto row = Tuple::deserialize(data, len, types);')
lines.append('        if (col_idx < (int)row.size() && std::holds_alternative<int64_t>(row[col_idx]))')
lines.append('            idx->insert(std::get<int64_t>(row[col_idx]), rid);')
lines.append('    });')
lines.append('    return {true, "OK: index created on " + table + "." + column};')
lines.append('}')
lines.append('')
lines.append('Value QueryEngine::eval_expr(const Expr *expr, const std::vector<Value> &row, const TableDef &def) const {')
lines.append('    if (expr->type == ExprType::LITERAL) return expr->literal;')
lines.append('    if (expr->type == ExprType::COLUMN_REF) {')
lines.append('        int idx = def.column_index(expr->col_name);')
lines.append('        if (idx < 0 || idx >= (int)row.size()) return std::monostate{};')
lines.append('        return row[idx];')
lines.append('    }')
lines.append('    if (expr->type == ExprType::BINARY_OP) {')
lines.append('        Value l = eval_expr(expr->left.get(), row, def);')
lines.append('        Value r = eval_expr(expr->right.get(), row, def);')
lines.append('        bool l_int = std::holds_alternative<int64_t>(l);')
lines.append('        bool r_int = std::holds_alternative<int64_t>(r);')
lines.append('        if (l_int && r_int) {')
lines.append('            int64_t lv = std::get<int64_t>(l), rv = std::get<int64_t>(r);')
lines.append('            if (expr->op == "=")  return (bool)(lv == rv);')
lines.append('            if (expr->op == "!=") return (bool)(lv != rv);')
lines.append('            if (expr->op == "<")  return (bool)(lv <  rv);')
lines.append('            if (expr->op == ">")  return (bool)(lv >  rv);')
lines.append('            if (expr->op == "<=") return (bool)(lv <= rv);')
lines.append('            if (expr->op == ">=") return (bool)(lv >= rv);')
lines.append('        }')
lines.append('        std::string ls = value_to_str(l), rs = value_to_str(r);')
lines.append('        if (expr->op == "=")  return (bool)(ls == rs);')
lines.append('        if (expr->op == "!=") return (bool)(ls != rs);')
lines.append('        if (expr->op == "<")  return (bool)(ls <  rs);')
lines.append('        if (expr->op == ">")  return (bool)(ls >  rs);')
lines.append('        if (expr->op == "<=") return (bool)(ls <= rs);')
lines.append('        if (expr->op == ">=") return (bool)(ls >= rs);')
lines.append('    }')
lines.append('    return std::monostate{};')
lines.append('}')
lines.append('')
lines.append('bool QueryEngine::eval_where(const Expr *expr, const std::vector<Value> &row, const TableDef &def) const {')
lines.append('    if (!expr) return true;')
lines.append('    Value result = eval_expr(expr, row, def);')
lines.append('    if (std::holds_alternative<bool>(result)) return std::get<bool>(result);')
lines.append('    return false;')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_insert(const InsertStmt &s) {')
lines.append('    const TableDef *def = catalog_->get_table(s.table);')
lines.append('    if (!def) return {false, "table \'" + s.table + "\' not found"};')
lines.append('    std::vector<Value> row(def->columns.size(), std::monostate{});')
lines.append('    if (s.columns.empty()) {')
lines.append('        if (s.values.size() != def->columns.size())')
lines.append('            return {false, "value count does not match column count"};')
lines.append('        row = s.values;')
lines.append('    } else {')
lines.append('        if (s.values.size() != s.columns.size())')
lines.append('            return {false, "column/value count mismatch"};')
lines.append('        for (size_t i = 0; i < s.columns.size(); i++) {')
lines.append('            int idx = def->column_index(s.columns[i]);')
lines.append('            if (idx < 0) return {false, "unknown column \'" + s.columns[i] + "\'"};')
lines.append('            row[idx] = s.values[i];')
lines.append('        }')
lines.append('    }')
lines.append('    auto bytes = Tuple::serialize(row);')
lines.append('    HeapFile &heap = get_heap(s.table);')
lines.append('    RID rid = heap.insert(bytes.data(), static_cast<uint16_t>(bytes.size()));')
lines.append('    for (size_t i = 0; i < def->columns.size(); i++) {')
lines.append('        if (def->columns[i].type == DataType::INT) {')
lines.append('            BTree *idx = idx_mgr_->get_index(s.table, def->columns[i].name);')
lines.append('            if (idx && std::holds_alternative<int64_t>(row[i]))')
lines.append('                idx->insert(std::get<int64_t>(row[i]), rid);')
lines.append('        }')
lines.append('    }')
lines.append('    return {true, "OK: 1 row inserted"};')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_select(const SelectStmt &s) {')
lines.append('    const TableDef *def = catalog_->get_table(s.table);')
lines.append('    if (!def) return {false, "table \'" + s.table + "\' not found"};')
lines.append('    std::vector<int> col_indices;')
lines.append('    std::vector<std::string> col_names;')
lines.append('    if (s.columns.empty()) {')
lines.append('        for (int i = 0; i < (int)def->columns.size(); i++) {')
lines.append('            col_indices.push_back(i);')
lines.append('            col_names.push_back(def->columns[i].name);')
lines.append('        }')
lines.append('    } else {')
lines.append('        for (auto &c : s.columns) {')
lines.append('            int idx = def->column_index(c);')
lines.append('            if (idx < 0) return {false, "unknown column \'" + c + "\'"};')
lines.append('            col_indices.push_back(idx);')
lines.append('            col_names.push_back(c);')
lines.append('        }')
lines.append('    }')
lines.append('    std::vector<DataType> types;')
lines.append('    for (auto &c : def->columns) types.push_back(c.type);')
lines.append('    QueryResult result;')
lines.append('    result.columns = col_names;')
lines.append('    HeapFile &heap = get_heap(s.table);')
lines.append('    // Try index lookup')
lines.append('    if (s.where && s.where->type == ExprType::BINARY_OP && s.where->op == "=") {')
lines.append('        Expr *left  = s.where->left.get();')
lines.append('        Expr *right = s.where->right.get();')
lines.append('        if (left->type == ExprType::COLUMN_REF &&')
lines.append('            right->type == ExprType::LITERAL &&')
lines.append('            std::holds_alternative<int64_t>(right->literal)) {')
lines.append('            BTree *idx = idx_mgr_->get_index(s.table, left->col_name);')
lines.append('            if (idx) {')
lines.append('                int64_t val = std::get<int64_t>(right->literal);')
lines.append('                auto rids = idx->lookup(val);')
lines.append('                char buf[PAGE_SIZE];')
lines.append('                for (auto &rid : rids) {')
lines.append('                    uint16_t len = heap.fetch(rid, buf, PAGE_SIZE);')
lines.append('                    if (len == 0) continue;')
lines.append('                    auto row = Tuple::deserialize(buf, len, types);')
lines.append('                    if (!eval_where(s.where.get(), row, *def)) continue;')
lines.append('                    std::vector<Value> projected;')
lines.append('                    for (int i : col_indices)')
lines.append('                        projected.push_back(i < (int)row.size() ? row[i] : std::monostate{});')
lines.append('                    result.rows.push_back(std::move(projected));')
lines.append('                }')
lines.append('                return result;')
lines.append('            }')
lines.append('        }')
lines.append('    }')
lines.append('    // Full scan fallback')
lines.append('    heap.scan([&](RID, const char *data, uint16_t len) {')
lines.append('        auto row = Tuple::deserialize(data, len, types);')
lines.append('        if (!eval_where(s.where.get(), row, *def)) return;')
lines.append('        std::vector<Value> projected;')
lines.append('        for (int idx : col_indices)')
lines.append('            projected.push_back(idx < (int)row.size() ? row[idx] : std::monostate{});')
lines.append('        result.rows.push_back(std::move(projected));')
lines.append('    });')
lines.append('    return result;')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_delete(const DeleteStmt &s) {')
lines.append('    const TableDef *def = catalog_->get_table(s.table);')
lines.append('    if (!def) return {false, "table \'" + s.table + "\' not found"};')
lines.append('    std::vector<DataType> types;')
lines.append('    for (auto &c : def->columns) types.push_back(c.type);')
lines.append('    std::vector<RID> to_delete;')
lines.append('    HeapFile &heap = get_heap(s.table);')
lines.append('    heap.scan([&](RID rid, const char *data, uint16_t len) {')
lines.append('        auto row = Tuple::deserialize(data, len, types);')
lines.append('        if (eval_where(s.where.get(), row, *def))')
lines.append('            to_delete.push_back(rid);')
lines.append('    });')
lines.append('    for (auto &rid : to_delete) heap.remove(rid);')
lines.append('    return {true, "OK: " + std::to_string(to_delete.size()) + " row(s) deleted"};')
lines.append('}')
lines.append('')
lines.append('QueryResult QueryEngine::exec_update(const UpdateStmt &s) {')
lines.append('    const TableDef *def = catalog_->get_table(s.table);')
lines.append('    if (!def) return {false, "table \'" + s.table + "\' not found"};')
lines.append('    std::vector<DataType> types;')
lines.append('    for (auto &c : def->columns) types.push_back(c.type);')
lines.append('    std::vector<std::pair<RID, std::vector<Value>>> to_update;')
lines.append('    HeapFile &heap = get_heap(s.table);')
lines.append('    heap.scan([&](RID rid, const char *data, uint16_t len) {')
lines.append('        auto row = Tuple::deserialize(data, len, types);')
lines.append('        if (!eval_where(s.where.get(), row, *def)) return;')
lines.append('        for (auto &[col, val] : s.assignments) {')
lines.append('            int idx = def->column_index(col);')
lines.append('            if (idx >= 0 && idx < (int)row.size()) row[idx] = val;')
lines.append('        }')
lines.append('        to_update.emplace_back(rid, std::move(row));')
lines.append('    });')
lines.append('    int count = 0;')
lines.append('    for (auto &[rid, row] : to_update) {')
lines.append('        heap.remove(rid);')
lines.append('        auto bytes = Tuple::serialize(row);')
lines.append('        heap.insert(bytes.data(), static_cast<uint16_t>(bytes.size()));')
lines.append('        count++;')
lines.append('    }')
lines.append('    return {true, "OK: " + std::to_string(count) + " row(s) updated"};')
lines.append('}')

with open(r'D:\mydb\src\query\QueryEngine.cpp', 'w') as f:
    f.write('\n'.join(lines))
print('written', len(lines), 'lines')
